### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ferringb**
I've got a fairly complex schema I've been working with; the fixes in this branch are pretty much everything I've ran into for py2.7 and have been addressing as I go along to make PSJ work for the given schema.

One additional; the nose-of-yeti tests really aren't covering much, and the approach enforced there really isn't providing much code reuse/gains for tests.  I've got a separate commit that converts the testcases from nose-of-yeti to straight unittests- I had to level that so I could actually do debugging of failed testcases (noy makes that effectively impossible).  Any interest?

### CODE REVIEW

**Comment by cwacekINV** [comment]
I'm game to convert the noy tests to unittest tests (could you do that in a separate PR so I can check that the test coverage is substantially the same). 

nose-of-yeti was something I found while putting this together, and while a pretty clever idea, I agree that it's far less usable and much more brittle.

**Comment by ferringb** [comment]
I'll open a seperate PR w/ the NOY code translated (already have it locally).  Also, 843f82 fixes issue #5; moreso, it makes the underlying error in the schema be exposed.

**Comment by Fitblip** [comment]
Hey guys,

I think this PR may have some larger issues...

After upgrading and running my tests I'm getting:
`ValidationError: 1 was more than or equal to 2`

Which should *never* happen.

**Comment by cwacek** [comment]
@Fitblip All of the current tests are checking out - do you have a specific test case that exhibits that?

**Pull request merged**
