### PR TITLE
Converting to string before logging

### PR DESCRIPTION
**Pull request by dmvieira**
This will enable json logger compatibility because lazy_format class is not json serializable

### CODE REVIEW

**Comment by cwacek** [comment]
The whole point of the`lazy_format` class is to be lazily evaluated (i.e. not actually do the string formatting unless it gets called by the logging statement). This is so that if you're not running at debug level you don't incur the string serialization cost anyway.

This change just makes it get evaluated immediately, which is no bueno. Would making the lazy format class implement json serializers be a better path?

**Comment by cwacek** [comment]
I was just reminded when looking into this that there's no sane way to make a class serializable automatically.

What logger are you using such that it's doing JSON serialization?

**Comment by dmvieira** [comment]
You can choose every json logging, but I'm using: https://pypi.org/project/sanic-json-logging/

This one will break too https://pypi.org/project/json-logging/ because logging expects a string type as input

**Comment by cwacek** [comment]
@dmvieira I just checked this with https://pypi.org/project/json-logging/ and it works fine. I showed working code below. I'm not familiar with sanic, so I don't know how to set up the other library to test it. 

The behavior is compatible with the Python logging API, as described here: https://docs.python.org/3/library/logging.html#logging.LogRecord.getMessage. I think the sanic logger just doesn't implement that behavior properly (should just call `str()` itself).

```
>>> import logging,json_logging
>>> import python_jsonschema_objects.util as util
>>> logging.basicConfig(level=logging.DEBUG)
>>> logger = logging.getLogger()
>>> json_logging.ENABLE_JSON_LOGGING = True
>>> json_logging.init_non_web()
>>> json_logging.config_root_logger()
>>> logger.info("Hello")
{"type": "log", "written_at": "2020-04-05T19:14:01.488Z", "written_ts": 1586114041488112000, "component_id": "-", "component_name": "-", "component_instance": 0, "logger": "hi", "thread": "MainThread", "level": "INFO", "line_no": 1, "module": "<stdin>", "msg": "Hello"}
>>> x = util.lazy_format("hi {}", "Diego")
>>> x
<python_jsonschema_objects.util.lazy_format object at 0x104c0a780>
>>> logger.info(x)
{"type": "log", "written_at": "2020-04-05T19:14:32.919Z", "written_ts": 1586114072919459000, "component_id": "-", "component_name": "-", "component_instance": 0, "logger": "hi", "thread": "MainThread", "level": "INFO", "line_no": 1, "module": "<stdin>", "msg": "hi Diego"}
```

**Pull request closed without merging**
